syntax = "proto3";

package {{ prefix_name }}_{{ suffix_name }};

option java_package = "{{ prefix_name }}.{{ suffix_name }}";

service {{ PrefixName }}{{ SuffixName }} {
    rpc Create{{ PrefixName }} ({{ PrefixName }}) returns ({{ PrefixName }});
    rpc Get{{ PrefixName }} (Get{{ PrefixName }}Request) returns ({{ PrefixName }});
    rpc List{{ PrefixName }}s (List{{ PrefixName }}sRequest) returns (List{{ PrefixName }}sResponse);
    rpc Update{{ PrefixName }} ({{ PrefixName }}) returns ({{ PrefixName }});
}

message {{ PrefixName }} {
    optional string id = 1;
    string display_name = 2;
}

message Get{{ PrefixName }}Request {
    string id = 1;
}

message List{{ PrefixName }}sRequest {
    int32 page_size = 1;
    string page_token = 2;
}

message List{{ PrefixName }}sResponse {
    repeated {{ PrefixName }} items = 1;
    string next_page_token = 2;
}
